#CREATING PROGRAM THAT MANAGES PASSWORDS AND ENCRYPTES THEM IN A TXT FILE (incomplete encryption)
from cryptography.fernet import Fernet #allows encryption for your passwords

#the pass function basically just passes and skips the part of code that is not being used
password = input("What is the master password? ")

'''
#you will run this function one time so that it runs a key file for you 
def key():
    key = Fernet.generate_key() #generate a key using the Fernet module
    with open('key.key', "wb") as keyfile: #open a file called key.key and wb means write in bytes 
        keyfile.write(key) #this function writes in the key that was generated by fernet 

key()
'''

def load_key(): #this function will now load this key
    file = open("key.key", 'rb')
    key = file.read()
    file.close()
    return key 

masterkey = load_key()
fer = Fernet(masterkey)

#encryption stopped here(unfinished)

def view(): #using a function
    with open('passwords.txt', 'r') as filename:
        for line in filename.readlines():

            print(line.strip()) #strips off the newline command for each line using strip method
            user,passwd = line.split("|") #split apart the username and password using the split method
            print("Username:" + user, "Password:" + passwd)

def add():
    name = input("Account name: ")
    password = input("Password: ")

    #file = open('password.txt', 'a') #this will open a file and append whatever into it howoever you would need to close the file manually
    #file.close() manually closing the file

    with open('passwords.txt ', 'a') as filename: #this with keyword will automatically close the file for you when you are done appending to it. 'a' | will just add stuff to the end of the file
    #this portion where the 'a' it can be used interchangeably such as words such as 'w'|which will override a file and clear and write over it|'r'| will just allow you to open and read the file 
        #the as f = the name of the file
        filename.write(name + "|" + password + "\n")

     

while True:
    mode = input("Would you like to add a new password or view existing ones (view,add) and q is to quit ")
    if mode =='q':
        break
    if mode == "view":
        view()
    elif mode == "add":
        add()
    else: 
        print("Invalid Mode")